### ISSUE TITLE
Question about Transaction.class

### ISSUE THREAD

**Issue by AlexanderTorchynskyi** [lightningj-org/lightningj#24]
### Subject of the issue
Hey guys thanks for the awesome lib, just have a question about `Transaction.class`. It looks like each transaction has `destination_addresses` but doesn't have the `from_address` did I miss something? Are there any ways to get from_address once I received the transaction? 
Thanks.

**Comment by herrvendil** [comment]
Hi Alexander

My library automatically generates that class from the LND RPC proto file. And when looking at the specification 

Here is the related message specification from the proto file:

    message Transaction {
      /// The transaction hash
      string tx_hash = 1 [ json_name = "tx_hash" ];

      /// The transaction amount, denominated in satoshis
      int64 amount = 2 [ json_name = "amount" ];

      /// The number of confirmations
      int32 num_confirmations = 3 [ json_name = "num_confirmations" ];

      /// The hash of the block this transaction was included in
      string block_hash = 4 [ json_name = "block_hash" ];

      /// The height of the block this transaction was included in
      int32 block_height = 5 [ json_name = "block_height" ];

      /// Timestamp of this transaction
      int64 time_stamp = 6 [ json_name = "time_stamp" ];

      /// Fees paid for this transaction
      int64 total_fees = 7 [ json_name = "total_fees" ];

      /// Addresses that received funds for this transaction
      repeated string dest_addresses = 8 [ json_name = "dest_addresses" ];
    }

I have also looked up current master of LND proto and there is no from field there either unfortunately.

**Comment by herrvendil** [comment]
Closing this issue, if there aren't any further questions on this subject.
