### ISSUE TITLE
Closing a channel returns wrong status information

### ISSUE THREAD

**Issue by gcomte** [lightningj-org/lightningj#37]
### Subject of the issue
When closing a channel, the closing works fine, but the information returned in Iterator<CloseStatusUpdate> is wrong. The "success" variable is set to false, but also the closing txid is wrong, such that blockstream.info/testnet does not find any transaction with the given transaction id (represented as hex).

### Your environment
* lightningj 0.6.1-beta
* Bitcoin Testnet

### Steps to reproduce
Close a transaction and check the data returned by the method closeChannel(CloseChannelRequest request)

### Expected behaviour
Return `"success": true` and correct txid

**Comment by herrvendil** [comment]
Hi
This seems strange, the lightningJ library only converts the underlying GRPC response from LND. But I will try to recreate the problem on my node and come back to you within a couple of days.

**Comment by gcomte** [comment]
Sooooo.... It turns out that I just have to reverse all the bytes received before i hex them and then I get the correct TXid. Yay!

Then the other issue with the `success` being `false`, it looks like this is indeed a problem of LND, and that they don't properly use this flag.

So, everything is fine for me now, feel free to close this issue :-)

**Comment by herrvendil** [comment]
Ok, closing it then.

Regards
Philip
