### ISSUE TITLE
0.12.0-Beta not available in maven central

### ISSUE THREAD

**Issue by selbert** [lightningj-org/lightningj#63]
### 0.12.0-Beta not available in maven central
I can't seem to find version 0.12.0-Beta on maven central 

https://search.maven.org/search?q=org.lightningj

**Comment by herrvendil** [comment]
Hi, sometimes it takes a couple of hours for maven central to update all repositories. I will try in an hour to verify that it was published properly.

**Comment by herrvendil** [comment]
Hi again I have searched maven now and it seems that it is publised, does it still not work for you?

https://search.maven.org/artifact/org.lightningj/lightningj/0.12.0-Beta/jar

**Comment by selbert** [comment]
It works, thanks!
