### ISSUE TITLE
com.sun:tools:jar must specify an absolute path but is ${tools.jar}

### ISSUE THREAD

**Issue by RajGoodF** [lightningj-org/lightningj#67]
### Subject of the issue
Errors occurred while build effective model from /home/raj/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-core/2.2.11/db0f76866c6b1e50084e03ee8cf9ce6b19becdb3/jaxb-core-2.2.11.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in com.sun.xml.bind:jaxb-core:2.2.11
Errors occurred while build effective model from /home/raj/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.2.11/2d4b554997fd01d1a2233b1529b22fc9ecc0cf5c/jaxb-impl-2.2.11.pom:
    'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} in com.sun.xml.bind:jaxb-impl:2.2.11

I am running lightningj with java 11 and gradle 7.1

### Your environment
* version of lightningj -> 0.13.1-Beta
* version and vendor of JDK -> Corretto 11
* your operationg systems. -> Ubuntu 20
* gradle version -> 7.1

**Comment by Shah-Moksh** [comment]
@herrvendil I think version of javaxb (2.2.11) causing error. Need to update that one.
