### ISSUE TITLE
Issue with list payments apis

### ISSUE THREAD

**Issue by vanditshah99** [lightningj-org/lightningj#92]
We are encountering a strange issue with our LND Node list payments api,

When directly quering the listpayments api using the cli we are getting result, show in image 1,  but when using library  lightningj we are not getting any response for this same set of input parameters,  as show in image two and three. What can be the issue with this? We are using 0.17.0 BETA 

![image](https://github.com/lightningj-org/lightningj/assets/114576838/751eb405-c86c-4afd-8055-22efbeafd400)
r LND Node, 
![image (12)](https://github.com/lightningj-org/lightningj/assets/114576838/2441077b-9a23-4620-8d21-e4e76f3149ad)

![image](https://github.com/lightningj-org/lightningj/assets/114576838/aef4f88c-0665-4336-b2e9-1b97a2947549)

@herrvendil @pvendil @theborakompanioni

**Comment by herrvendil** [comment]
Great that this was sorted out.
